apiVersion: v1
kind: Service
metadata:
  name: ai-resume-analyzer-service
  labels:
    app: ai-resume-analyzer
spec:
  type: NodePort
  selector:
    app: ai-resume-analyzer
  ports:
    - name: http
      port: 10000
      targetPort: 10000
      nodePort: 30080